### PR TITLE
triton/apps/mathematica.rst: Update docs, Triton issue #561

### PR DESCRIPTION
**Pull request by rkdarst**
Can someone who knows about mathematica check this?  @aalto-kenny, do
you know, or know anyone who is an expert?

### CODE REVIEW

**Comment by aalto-kenny** [comment]
I'll try to check this next week when I'm in office. If I don't, please feel free to remind me. Harri Hakula is a Mathematica expert, but I'm unsure about how much he's using Mathematica on Triton.

**Comment by rkdarst** [comment]
I'd say that you don't need to know anything about Triton to sanity check the docs, just know something about non-GUI usage.  Thanks!

I'll also ask Harri now, thanks for that hint.

**Comment by rkdarst** [comment]
Contacted Harri, he'll help to update things once vacations are over.

**Comment by aalto-kenny** [comment]
Thanks Richard, I'm sure he knows the answers off the shelf.

By the way, I noticed a problem with a couple of the links to the documentation, they don't render as I guess they should. E.g. in "interactive shell on a node".

**Comment by rkdarst** [comment]
Things we discussed:
- Make Mathematica 12 available (but mathematica 11 has the `wolframscript` interface already)
- Use environment variable `SLURM_CPUS_PER_TASK` to set number of cores for multi-kernel parallelization
- Use `wolframscript` for the batch jobs.
- Different ways of parallelizing.

**Comment by jabl** [comment]
Merged this. For further improvements please open a new PR.

**Pull request merged**
